# -*- coding: utf-8 -*-
"""Data analysis of amazon top 50 selling books.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_sSY32tdxAwpC872ErBkALu-pHm1w6FF
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv('/content/drive/MyDrive/ML Project/bestsellers with categories.csv')

data.head()

data.columns

data.shape

data.describe()

data.info()

data.isnull().any()

data.isnull().sum()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(data.isnull())
plt.show()

data.median()

plt.figure(figsize= (20,15))
plt.subplot(4,4,1)
sns.boxplot(data['User Rating'])

plt.subplot(4,4,2)
sns.boxplot(data['Reviews'])

plt.subplot(4,4,3)
sns.boxplot(data['User Rating'])

data['Price'] = data['Price'].clip(lower=data['Price'].quantile(0.05), upper = data['Price'].quantile(0.95))

data['User Rating'] = data['User Rating'].clip(lower=data['User Rating'].quantile(0.05), upper = data['User Rating'].quantile(0.95))

data['Reviews'] = data['Reviews'].clip(lower=data['Reviews'].quantile(0.05), upper = data['Reviews'].quantile(0.95))

plt.figure(figsize=(20,15))
plt.subplot(4,4,1)
sns.boxplot(data['Price'])
plt.subplot(4,4,2)
sns.boxplot(data['User Rating'])
plt.subplot(4,4,3)
sns.boxplot(data['Reviews'])

plt.figure(figsize=(16,4))
sns.countplot(x = 'Year', data=data, hue='Name')